name: Docker Build CI

on:
 push: 
    branches: [ main ]

jobs:
  biuld:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name : Login to Docker Hub
      run :  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t devops-monitoring-app:latest .

    - name : Push Docker image
      run : docker push ${{ secrets.DOCKER_USERNAME }}/devops-monitoring-app 